site_name: algebraic-immunity
site_url: https://LucaBonemino.github.io/algebraic-immunity/
theme: readthedocs
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google
            show_source: false
